import { ORAL_MAX_CONSECUTIVE_WEAK, ORAL_MAX_DEPTH } from "./config";
import type { CognitiveLevelValue, ExamAnswerClassificationValue } from "./types";

/**
 * OralExamEngine's deterministic depth/progression rules (spec §28-31).
 * Question *content* (the examiner's actual message) is generated by
 * exam-evaluator.ts's generateOralExaminerMessage() — this module only
 * decides WHEN to go deeper on the same concept vs. move to the next one,
 * exactly mirroring how Phase 7's socratic.ts separates decision from
 * language generation.
 */

const DEPTH_TO_COGNITIVE_LEVEL: Record<number, CognitiveLevelValue> = {
  1: "RECALL",
  2: "UNDERSTAND",
  3: "APPLY",
  4: "ANALYZE",
  5: "EVALUATE",
};

export function cognitiveLevelForDepth(depth: number): CognitiveLevelValue {
  return DEPTH_TO_COGNITIVE_LEVEL[Math.min(ORAL_MAX_DEPTH, Math.max(1, depth))];
}

const STRONG: ExamAnswerClassificationValue[] = ["CORRECT", "PARTIALLY_CORRECT"];

/**
 * Whether to move on to a new concept rather than keep probing this one
 * (spec §30 — "Do not always reach level 5. Adapt to performance."): either
 * the student has been struggling for two answers in a row, or they've
 * just nailed the deepest level there is.
 */
export function shouldAdvanceToNextConcept(depth: number, consecutiveWeak: number): boolean {
  if (consecutiveWeak >= ORAL_MAX_CONSECUTIVE_WEAK) return true;
  if (depth >= ORAL_MAX_DEPTH) return true;
  return false;
}

export interface OralProgressionResult {
  nextDepth: number;
  consecutiveWeak: number;
  advanceToNextConcept: boolean;
}

/**
 * Given the classification of the student's last response, decides the
 * next depth level (deeper on a strong answer, held or stepped back on a
 * weak one) and whether this concept's line of questioning is done (spec
 * §29-31 — challenge, clarify, probe, but never grind past two weak
 * answers in a row).
 */
export function nextOralProgression(currentDepth: number, consecutiveWeak: number, classification: ExamAnswerClassificationValue): OralProgressionResult {
  const isStrong = STRONG.includes(classification);
  const nextConsecutiveWeak = isStrong ? 0 : consecutiveWeak + 1;
  const nextDepth = isStrong ? Math.min(ORAL_MAX_DEPTH, currentDepth + 1) : currentDepth;

  return {
    nextDepth,
    consecutiveWeak: nextConsecutiveWeak,
    advanceToNextConcept: shouldAdvanceToNextConcept(isStrong ? nextDepth : currentDepth, nextConsecutiveWeak),
  };
}
